# mkdocs.yml -- MkDocs configuration, all *.md files relative to docs/
site_name: TekDash Knowledgebase
pages:
- Home: 'index.md'
- Windows: 
  - Windows Home: 'windows/windows.md'
  - Hard Drive Failure: 'windows/hard_drive/hardDriveFailure.md'
  - Virus Removal: 'windows/virus/virus-removal-checklist.md'
- Mac:
  - iTunes keeps saying my password is incorrect: 'mac/appleID/appleIDPasswordIncorrect.md'

theme: readthedocs